---
encryption_key: "germanopen2019"
port: 1234
target_ips:
  - 192.168.17.0

topics:
  - /rosout
  - /joint_states
  - /DynamixelController/command
  - /robot_state
  - /cmd_vel
  - /walking_debug
  - /imu/data
  - /tf
  - /tf_static
  - /debug/dsd/body_behavior
  - /debug/dsd/head_behavior
  - /debug/dsd/hcm
  - /move_base_simple/goals
  - /team_data
  - /ball_relative
  - /obstacles_relative
  - /amcl_pose
  - /line_relative
  - /gamestate
  - /animation/goal
  - /animation/cancel
  - /animation/status
  - /animation/result
  - /animation/feedback
  - /animation
